title: Pragmatic Lightning
description: >-
  Build a fully funcitonal Bitcoin Lightning app in no time.
theme: jekyll-theme-leap-day
markdown: kramdown
exclude:
  - .idea
  - rain-report/bitcoind_data
  - rain-report/lnd_data